FROM ghcr.io/areif-dev/distrobox-images/fedora-base:latest

RUN mkdir -p /tmp/extras

RUN dnf install -y \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

RUN dnf install -y \
    discord \
    steam 

COPY ./export-apps /usr/bin/export-apps
COPY ./extras.sh /tmp/extras/extras.sh
WORKDIR /tmp/extra
RUN /tmp/extras/extras.sh && \
    rm -rf /tmp/extras

# Update and clean up 
RUN dnf upgrade -y && \
    dnf clean all && \
    dnf autoremove -y
