FROM ghcr.io/areif-dev/distrobox-images/fedora-base:latest

RUN mkdir -p /tmp/extras

RUN dnf5 install -y \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

RUN dnf5 upgrade -y

RUN dnf5 install -y \
    gamemode \
    steam 

COPY ./extras.sh /tmp/extras/extras.sh
WORKDIR /tmp/extra
RUN /tmp/extras/extras.sh && \
    rm -rf /tmp/extras

# Clean up 
RUN dnf5 clean all && \
    dnf5 autoremove -y

COPY ./distrobox-export-lists.sh /etc/distrobox-export-lists.sh
