FROM quay.io/fedora/fedora-minimal:42

# Speed up DNF
RUN sed -i 's/.*max_parallel_downloads=.*//g' /etc/dnf/dnf.conf && \
    sed -i 's/.*fastestmirror=.*//g' /etc/dnf/dnf.conf && \
    echo 'max_parallel_downloads=15' | tee -a /etc/dnf/dnf.conf && \
    echo 'fastestmirror=True' | tee -a /etc/dnf/dnf.conf

RUN dnf5 upgrade -y

# Install missing Distrobox dependencies
RUN dnf5 install -y \
    bash-completion \
    bc \
    bzip2 \
    curl \
    diffutils \
    findutils \
    gnupg2 \
    hostname \
    iproute \
    iputils \
    keyutils \
    krb5-libs \
    less \
    lsof \
    man-db \
    man-pages \
    ncurses \
    nss-mdns \
    openssh-clients \
    pam \
    passwd \
    pigz \
    pinentry \
    procps-ng \
    rsync \
    shadow-utils \
    sudo \
    tcpdump \
    time \
    traceroute \
    tree \
    tzdata \
    unzip \
    util-linux \
    vte-profile \
    wget \
    which \
    whois \
    words \
    xorg-x11-xauth \
    xz \
    zip \
    zsh

# Update and clean up 
RUN dnf5 clean all && \
    dnf5 autoremove -y

COPY ./export-apps /usr/bin/export-apps
