#!/usr/bin/env bash 

source /etc/distrobox-export-lists.sh

for app in "${apps[@]}"; do 
    distrobox-export --app "$app"
done

for bin in "${bins[@]}"; do 
    distrobox-export --bin "$(which $bin)"
done

for item in "${both[@]}"; do 
    distrobox-export --app "$item"
    distrobox-export --bin "$(which $item)"
done
