FROM ghcr.io/areif-dev/distrobox-images/fedora-base:latest

# Install user software
RUN dnf install -y \
    chromium \
    gimp \
    hledger \
    libreoffice \
    thunderbird

# Virtualization packages 
RUN dnf install -y \
    libvirt \
    libvirt-daemon-config-network \
    libvirt-daemon-kvm \
    qemu-kvm \
    virt-manager \
    libguestfs-tools \
    python3-libguestfs


# Update and clean up 
RUN dnf upgrade -y && \
    dnf clean all && \
    dnf autoremove -y

COPY ./distrobox-export-lists.sh /etc/distrobox-export-lists.sh
