FROM ghcr.io/areif-dev/distrobox-images/fedora-base:latest

# Install user software
RUN dnf install -y \
    keepassxc \
    kpcli \
    krita \
    libreoffice \
    perl-Authen-OATH \
    perl-Convert-Base32

# Update and clean up 
RUN dnf upgrade -y && \
    dnf clean all && \
    dnf autoremove -y
