FROM ghcr.io/areif-dev/distrobox-images/fedora-base:latest

# Install user software
RUN dnf5 install -y \
    gimp \
    hledger \
    libreoffice \
    thunderbird

# Virtualization packages 
RUN dnf5 install -y \
    libvirt \
    libvirt-daemon-config-network \
    libvirt-daemon-kvm \
    qemu-kvm \
    virt-manager \
    libguestfs-tools \
    python3-libguestfs


# Update and clean up 
RUN dnf5 upgrade -y && \
    dnf5 clean all && \
    dnf5 autoremove -y

COPY ./distrobox-export-lists.sh /etc/distrobox-export-lists.sh
