FROM ghcr.io/areif-dev/distrobox-images/fedora-base:latest

# Install user software
RUN dnf install -y \
    '@development-tools' \
    butane \
    jq \
    mingw32-gcc \
    mingw64-gcc \
    neovim \
    nodejs \
    python \
    python3 \
    python3-pip \
    rpmdevtools \
    rpmlint \
    rustup \
    rust-analyzer \
    sqlite3 \
    typescript \
    zsh-autosuggestions

RUN mkdir -p /tmp/extras
COPY ./extras.sh /tmp/extras/extras.sh
WORKDIR /tmp/extra
RUN /tmp/extras/extras.sh && \
    rm -rf /tmp/extras

# Update and clean up 
RUN dnf upgrade -y && \
    dnf clean all && \
    dnf autoremove -y
