FROM ghcr.io/areif-dev/distrobox-images/fedora-base:latest

RUN dnf5 upgrade -y

# Install user software
RUN dnf5 install -y \
    '@development-tools' \
    butane \
    clang-devel \
    jq \
    mingw32-gcc \
    mingw64-gcc \
    neovim \
    nodejs \
    openssl-devel \
    python \
    python3 \
    python3-pip \
    rpmdevtools \
    rpmlint \
    rustup \
    rust-analyzer \
    sqlite3 \
    zsh-autosuggestions

# Install language servers globally for use with neovim
RUN npm i -g vscode-langservers-extracted typescript-language-server
RUN pip install pyright

RUN mkdir -p /tmp/extras
COPY ./extras.sh /tmp/extras/extras.sh
WORKDIR /tmp/extra
RUN /tmp/extras/extras.sh && \
    rm -rf /tmp/extras

# Clean up 
RUN dnf5 clean all && \
    dnf5 autoremove -y
