FROM quay.io/fedora/fedora:40

# Install missing Distrobox dependencies
RUN dnf install -y \
    bash-completion \
    bc \
    bzip2 \
    curl \
    diffutils \
    findutils \
    gnupg2 \
    hostname \
    iproute \
    iputils \
    keyutils \
    krb5-libs \
    less \
    lsof \
    man-db \
    man-pages \
    ncurses \
    nss-mdns \
    openssh-clients \
    pam \
    passwd \
    pigz \
    pinentry \
    procps-ng \
    rsync \
    shadow-utils \
    sudo \
    tcpdump \
    time \
    traceroute \
    tree \
    tzdata \
    unzip \
    util-linux \
    vte-profile \
    wget \
    which \
    whois \
    words \
    xorg-x11-xauth \
    xz \
    zip \
    zsh


RUN dnf install -y 'dnf-command(copr)' && \
    dnf copr enable atim/starship -y

# Install user software
RUN dnf install -y \
    '@Development Tools' \
    jq \
    neovim \
    nodejs \
    rpmdevtools \
    rpmlint \
    rustup \
    python \
    python3 \
    python3-pip \
    starship \
    zsh-autosuggestions

RUN mkdir -p /tmp/extras
COPY ./extras.sh /tmp/extras/extras.sh
WORKDIR /tmp/extra
RUN /tmp/extras/extras.sh && \
    rm -rf /tmp/extras

# Update and clean up 
RUN dnf upgrade -y && \
    dnf clean all && \
    dnf autoremove -y
